### ISSUE TITLE
TODO Tracking

### ISSUE THREAD

**Issue by gcartier94** [gcartier94/make-it-flow#1]
- [x] Implement YAML base parser
  - [x] Install yml npm package
- [x] Identify Workflow related attributes
- [ ] Compile YAML into valid XML
  - [ ] Implement Workflow metadata xml compilation
  - [ ] Implement Workflow variable compilation
  - [ ] Implement Workflow step compilation
- [ ] Implement XML validation against schema
